name: Add iOS Support and Export Tarball

on:
  workflow_dispatch:

jobs:
  prepare-ios-support:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get full history

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Can be adjusted to beta or dev as needed

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate API Client
        run: |
          chmod +x ./gen-client.sh
          ./gen-client.sh

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Create iOS Folder
        run: flutter create .

      - name: Archive Project
        run: tar -czf flutter_project.tar.gz .

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: flutter-ios-project
          path: flutter_project.tar.gz
