name: Build Flutter iOS Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Can be adjusted to beta or dev as needed

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Generate API Client
        run: |
          chmod +x ./gen-client.sh
          ./gen-client.sh

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install
          cd ..

      - name: Setup Signing Certificates
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          DEVELOPER_CERTIFICATE_BASE64: ${{ secrets.DEVELOPER_CERTIFICATE_BASE64 }}
          DEVELOPER_CERTIFICATE_PASSWORD: ${{ secrets.DEVELOPER_CERTIFICATE_PASSWORD }}
        run: |
          chmod +x ./scripts/setup-signing-certs.sh
          ./scripts/setup-signing-certs.sh

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Archive iOS
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/Runner.xcarchive \
          clean archive \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="YourProvisioningProfileName" \
          DEVELOPMENT_TEAM="YourTeamID"

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/Runner.xcarchive \
          -exportPath $PWD/build/Runner \
          -exportOptionsPlist ios/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: Runner.ipa
          path: build/Runner/Runner.ipa
